# This is a basic workflow to help you get started with Actions

name: Poliastro Website CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the sources branch
  push:
    branches: 
      - sources
      - 'content'
  
  pull_request:
    branches: 
      - sources
      - 'content'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Builds the WebPages locally before Deployment
  build:
    # Runner Type(s)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Set up Python Environment based on the version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Installations for all the dependencies 
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.in
      # Add the support plugins required & builds the webpages in HTML format
      - name: Build the webpages
        run: |
            git submodule update --init --recursive
            make html

    # Deployment to GH Pages
  deploy:
    # Runner Type(s)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9]

    steps:
      - name: Displaying Python Versions
        run: python -c "import sys; print(sys.version)"

    # # Uncomment for deployment
    # steps:
    # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2
    # # Set up Python Environment based on the version
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}
    # # Installations for all the dependencies 
    # - name: Install dependencies
    #   run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.in
    # # Add the support plugins required & builds the webpages in HTML format
    # - name: Build the webpages
    #   run: |
    #       git submodule update --init --recursive
    #       make html
    # - name: Deployment to Github Pages 
    #   run: |
    #       make publish-to-github